// src/app/api/executive/approvals/pending/route.ts
import { NextResponse } from "next/server";
import { orgIdsForUser, requireUser, safeStr } from "../_lib";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function noStoreJson(data: unknown, init?: ResponseInit) {
  return NextResponse.json(data, {
    ...(init ?? {}),
    headers: {
      "Cache-Control": "no-store, no-cache, must-revalidate, proxy-revalidate",
      Pragma: "no-cache",
      Expires: "0",
      ...(init?.headers ?? {}),
    },
  });
}

export async function GET(req: Request) {
  const url = new URL(req.url);
  const limit = Math.min(Number(url.searchParams.get("limit") ?? "200"), 500);

  try {
    const { supabase, user } = await requireUser();
    const orgIds = await orgIdsForUser(supabase, user.id);

    if (!orgIds.length) {
      return noStoreJson({ ok: true, scope: "org", orgId: null, items: [] }, { status: 200 });
    }

    const orgId = orgIds[0]; // single-org mode

    // 1) Prefer exec cache (generated by cron)
    const cacheRes = await supabase
      .from("exec_approval_cache")
      .select("*")
      .eq("organisation_id", orgId)
      .order("created_at", { ascending: false })
      .limit(limit);

    if (!cacheRes.error && (cacheRes.data?.length ?? 0) > 0) {
      return noStoreJson(
        {
          ok: true,
          scope: "org",
          orgId,
          source: "exec_approval_cache",
          items: cacheRes.data ?? [],
        },
        { status: 200 }
      );
    }

    // 2) Fallback: compute from v_pending_artifact_approvals (org-scoped)
    const pendingRes = await supabase
      .from("v_pending_artifact_approvals")
      .select("*")
      .in("organisation_id", orgIds)
      .order("created_at", { ascending: false })
      .limit(limit);

    if (pendingRes.error) {
      return noStoreJson(
        { ok: false, error: "pending_approvals_failed", message: pendingRes.error.message },
        { status: 500 }
      );
    }

    return noStoreJson(
      {
        ok: true,
        scope: "org",
        orgId,
        source: "v_pending_artifact_approvals",
        items: pendingRes.data ?? [],
      },
      { status: 200 }
    );
  } catch (e: any) {
    const msg = safeStr(e?.message || e || "pending approvals failed");
    return noStoreJson({ ok: false, error: "pending_approvals_failed", message: msg }, { status: 500 });
  }
}