import "server-only";

import { NextResponse } from "next/server";
import { createClient } from "@/utils/supabase/server";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const revalidate = 0;

function noStoreJson(data: unknown, init?: ResponseInit) {
  const res = NextResponse.json(data, init);
  res.headers.set("Cache-Control", "no-store, no-cache, must-revalidate, proxy-revalidate");
  res.headers.set("Pragma", "no-cache");
  res.headers.set("Expires", "0");
  return res;
}

function safeStr(x: any) {
  return typeof x === "string" ? x : x == null ? "" : String(x);
}

export async function GET(req: Request) {
  try {
    const url = new URL(req.url);
    const limit = Math.min(Number(url.searchParams.get("limit") ?? "200"), 500);

    const supabase = await createClient();

    // Identify the current user (cookie session)
    const {
      data: { user },
      error: userErr,
    } = await supabase.auth.getUser();

    if (userErr || !user) {
      return noStoreJson({ ok: false, error: "unauthorized" }, { status: 401 });
    }

    // Single-org mode: derive org from profile
    const { data: profile, error: profileErr } = await supabase
      .from("profiles")
      .select("active_organisation_id")
      .eq("user_id", user.id)
      .maybeSingle();

    if (profileErr) {
      return noStoreJson(
        { ok: false, error: "profile_load_failed", message: profileErr.message },
        { status: 500 }
      );
    }

    const orgId = safeStr(profile?.active_organisation_id);
    if (!orgId) {
      return noStoreJson({ ok: false, error: "no_active_org" }, { status: 400 });
    }

    // Read the executive cache generated by cron
    const { data, error } = await supabase
      .from("exec_approval_cache")
      .select("*")
      .eq("organisation_id", orgId)
      .order("computed_at", { ascending: false })
      .limit(limit);

    if (error) {
      return noStoreJson(
        { ok: false, error: "exec_cache_read_failed", message: error.message },
        { status: 500 }
      );
    }

    return noStoreJson({
      ok: true,
      scope: "org",
      orgId,
      source: "exec_approval_cache",
      items: data ?? [],
    });
  } catch (e: any) {
    return noStoreJson(
      { ok: false, error: "pending_approvals_failed", message: e?.message ?? String(e) },
      { status: 500 }
    );
  }
}