// Generates a PDF-ready HTML digest by calling the digest API
import "server-only";
import { NextResponse } from "next/server";
import { createClient } from "@/utils/supabase/server";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const ss = (x: any) => typeof x === "string" ? x : x == null ? "" : String(x);
const sn = (x: any) => { const n = Number(x); return isFinite(n) ? n : 0; };

function fmtDate(iso: string | null | undefined) {
  if (!iso) return "—";
  const d = new Date(iso); if (!isFinite(d.getTime())) return "—";
  return d.toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" });
}

function fmtDateShort(iso: string | null | undefined) {
  if (!iso) return "—";
  const d = new Date(iso); if (!isFinite(d.getTime())) return "—";
  return d.toLocaleDateString("en-GB", { day: "2-digit", month: "short" });
}

function ragColor(status: string) {
  const s = ss(status).toLowerCase();
  if (s === "overdue" || s === "breached" || s === "overdue_undecided" || s === "high") return "#e11d48";
  if (s === "warn" || s === "at_risk" || s === "medium") return "#d97706";
  return "#059669";
}

function ragLabel(status: string) {
  const s = ss(status).toLowerCase();
  if (s === "overdue" || s === "breached" || s === "overdue_undecided") return "BREACHED";
  if (s === "warn" || s === "at_risk") return "AT RISK";
  if (s === "high") return "HIGH RISK";
  if (s === "medium") return "MEDIUM RISK";
  return "OK";
}

function buildHtml(digest: any, days: number): string {
  const s = digest.sections;
  const sum = digest.summary;
  const genDate = fmtDate(digest.generated_at);
  const windowLabel = `Last ${days} day${days !== 1 ? "s" : ""}`;

  const sectionHeader = (title: string, count?: number) => `
    <div style="display:flex;align-items:center;gap:10px;margin:28px 0 12px;border-bottom:2px solid #e2e8f0;padding-bottom:8px;">
      <div style="font-size:13px;font-weight:800;color:#0f172a;text-transform:uppercase;letter-spacing:0.1em;">${title}</div>
      ${count !== undefined ? `<div style="background:#6366f1;color:white;border-radius:20px;padding:1px 8px;font-size:10px;font-weight:700;">${count}</div>` : ""}
    </div>`;

  const statCard = (label: string, value: string | number, color: string) => `
    <div style="background:#f8faff;border:1px solid #e2e8f0;border-radius:10px;padding:12px 14px;text-align:center;flex:1;">
      <div style="font-size:22px;font-weight:800;color:${color};font-family:monospace;line-height:1;">${value}</div>
      <div style="font-size:9px;color:#94a3b8;font-weight:700;text-transform:uppercase;letter-spacing:0.1em;margin-top:4px;">${label}</div>
    </div>`;

  const tableRow = (cells: string[], isHeader = false) => `
    <tr style="background:${isHeader ? "#f1f5f9" : "white"};">
      ${cells.map(c => `<td style="padding:7px 10px;font-size:${isHeader ? "9px" : "11px"};font-weight:${isHeader ? "700" : "400"};color:${isHeader ? "#64748b" : "#374151"};border-bottom:1px solid #f1f5f9;">${c}</td>`).join("")}
    </tr>`;

  const badge = (text: string, color: string) =>
    `<span style="display:inline-block;border-radius:20px;padding:2px 8px;font-size:9px;font-weight:700;background:${color}18;border:1px solid ${color}44;color:${color};">${text}</span>`;

  return `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"/><style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: sans-serif; padding: 40px; color: #374151; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
  @media print { body { -webkit-print-color-adjust: exact; } }
</style></head>
<body>
  <div style="border-bottom:3px solid #6366f1; padding-bottom:20px; margin-bottom:28px;">
    <h1 style="font-size:26px; color:#0f172a;">Portfolio Governance Report</h1>
    <div style="color:#64748b;">${windowLabel} · Generated ${genDate}</div>
  </div>

  <div style="display:flex; gap:10px; margin-bottom:28px;">
    ${statCard("Pending", sum.pending_total, "#6366f1")}
    ${statCard("Breached", sum.breached_total, "#e11d48")}
    ${statCard("Decisions", sum.decisions_total, "#0f172a")}
    ${statCard("High Risk", sum.at_risk_projects, "#e11d48")}
  </div>

  ${sectionHeader("SLA Breaches", s.sla_breaches.total)}
  <table>
    ${tableRow(["Project", "Approver"], true)}
    ${s.sla_breaches.items.map((r: any) => tableRow([ss(r?.project_title), ss(r?.approver_label)])).join("")}
  </table>

  ${sectionHeader("PM Performance")}
  <table>
    ${tableRow(["PM", "Projects", "Approve Rate", "Overdue"], true)}
    ${s.pm_performance.map((pm: any) => tableRow([
      ss(pm?.full_name), 
      String(pm?.projects_managed), 
      pm?.approval_rate ? `${pm.approval_rate}%` : "N/A",
      String(pm?.overdue)
    ])).join("")}
  </table>

  <div style="margin-top:40px; font-size:10px; color:#94a3b8;">Generated by Aliena AI · Confidential</div>
</body></html>`;
}

export async function GET(req: Request) {
  try {
    const url = new URL(req.url);
    const days = Math.min(Math.max(sn(url.searchParams.get("days") ?? "7"), 1), 90);
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return new NextResponse("Unauthorized", { status: 401 });

    const digestResp = await fetch(`${url.origin}/api/executive/digest?days=${days}`, {
      headers: { Cookie: req.headers.get("cookie") ?? "" },
    });
    const json = await digestResp.json();
    const html = buildHtml(json.digest, days);

    return new NextResponse(html, { headers: { "Content-Type": "text/html; charset=utf-8" } });
  } catch (e: any) {
    return new NextResponse(e.message, { status: 500 });
  }
}
