import type { ChangeItem } from "./types";

export const mockChanges: ChangeItem[] = [
  {
    id: "CR-001",
    title: "Extend firewall scope for vendor access",
    requester: "A. Mensah",
    summary: "Vendor requires temporary ingress rules to access staging. Ensure least privilege and time-boxing.",
    status: "new",
    priority: "High",
    tags: ["Security", "Vendor"],
    aiImpact: { days: 3, cost: 1200, risk: "Medium: exposure if not time-boxed" },
    justification: "Enable vendor to perform deployment verification.",
    financial: "Minor: admin effort only.",
    schedule: "May add 2–3 days lead time if approvals delayed.",
    risks: "Misconfigured rules; access creep.",
    dependencies: "Security approval, vendor IPs confirmed.",
  },
  {
    id: "CR-002",
    title: "Add additional test environment capacity",
    requester: "J. Smith",
    summary: "Provision extra VM capacity to support parallel testing and reduce queue time.",
    status: "analysis",
    priority: "Medium",
    tags: ["Infra", "Testing"],
    aiImpact: { days: 5, cost: 4200, risk: "Low: standard build" },
  },
  {
    id: "CR-003",
    title: "Update DNS records for new app endpoint",
    requester: "S. Patel",
    summary: "Cutover to new endpoint. Requires coordinated comms and rollback plan.",
    status: "review",
    priority: "Critical",
    tags: ["Network", "Cutover"],
    aiImpact: { days: 2, cost: 800, risk: "High: service disruption if misconfigured" },
  },
  {
    id: "CR-004",
    title: "Patch database minor version",
    requester: "Ops Team",
    summary: "Security patching per policy. Planned outage window required.",
    status: "in_progress",
    priority: "High",
    tags: ["DB", "Security"],
    aiImpact: { days: 1, cost: 0, risk: "Medium: rollback complexity" },
  },
];
